# use ipython -i functest.py
import pyras
client = pyras.RemoteCommandClient('127.0.0.1')
print client.info()
client.register('echo "Hello"')
print client.info()
client.start(1)
client.register('while true; do echo "oh no!"; done')
print client.info()
client.start(2)
print client.info()
client.stop(2)
client.run('echo "hello"')
client.unregister(2)
print client.info()
client.register('echo "1"', 'group1')
client.register('echo "2"', 'group1')
client.register('echo "3"', 'group1')
client.register('echo "4"', 'group1')
client.register('echo "5"', 'group1')
client.register('echo "6"', 'group1')
client.register('echo "7"', 'group1')
print client.info()
client.start_group('group1')
client.register('echo "8"', 'group1')
client.register('echo "9"', 'group1')
client.stop_group('group1')
client.start_group('group1')
print client.info()
print client.read('README.md', 0, 20)
print client.read_end('README.md', 20)
cid = client.register(r'for i in `seq 4`; do (while true; do echo $i; done &) ; done')
client.start(cid)
print client.info()
client.stop(cid)
print client.info()
